function fractals(F,Fprime,z0,d,n)
   % Fractals.  fractals(F,Fprime,z0,d,n).
   % Investigate fractal images generated by Newton's method
   % for the function F(z) with derivative Fprime(z)
   % started on the (n+1)-by-(n+1) complex grid centered at
   % the point z0 with half-width d.
      
      xs = real(z0)+[-1:2/n:1]*d;
      ys = imag(z0)+[-1:2/n:1]*d;
      [y,x] = ndgrid(ys,xs);
      z = x+1i*y;
      kounts = zeros(size(z));
      for k = 1:length(z(:))
         [z(k),kounts(k)] = newton_contour(F,Fprime,z(k));
      end
   
      figure(1)
      levels = min(kounts(:)) + [0:10];
      contourf(xs,ys,kounts,levels)
      colorbar
      colormap jet
      axis square
   
      figure(2)
      zone = round(atan2(imag(z),real(z))/pi);
      contourf(xs,ys,zone,-1:1)
      colorbar('Ticks',(2/3)*(-1:1),'Ticklabels',{'-2\pi/3',0,'2*\pi/3'})
      c = [1 1 0; 0 1 1; 1 0 1];
      colormap(c)
      axis square
   end 