function s = PartSum_mix(a,eh, e2h, n)
% This function performs the summation of the terms generated by the
% product of weights and nodes

ekh = eh;
s = Term_mix(a,ekh);
for k = 2 : n
    ekh = ekh * e2h;
    s = s + Term_mix(a,ekh);
end
end
